# Generated by Django 5.2.4 on 2025-08-10 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=45)),
                ('sucursal', models.CharField(db_column='sucursal', max_length=45)),
                ('referencia1', models.CharField(db_column='referencia1', max_length=45)),
                ('referencia2', models.CharField(blank=True, db_column='referencia2', max_length=45, null=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('motivo', models.CharField(db_column='motivo', max_length=50)),
                ('factura_venta', models.CharField(blank=True, db_column='facturaVenta', max_length=30, null=True)),
                ('recibo_caja', models.CharField(blank=True, db_column='reciboCaja', max_length=20, null=True)),
                ('comentario', models.CharField(blank=True, db_column='comentario', max_length=150, null=True)),
                ('responsable', models.ForeignKey(db_column='responsable', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='users.acudiente')),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
    ]
