# Generated by Django 5.2.4 on 2025-08-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuenta',
            field=models.CharField(choices=[('5031', '5031'), ('5032', '5032')], db_column='cuenta', default='5031', max_length=4),
        ),
    ]
