# Generated by Django 5.2.4 on 2025-08-12 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pago_cuenta'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='responsable',
            field=models.ForeignKey(blank=True, db_column='responsable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='users.acudiente'),
        ),
    ]
