# Generated by Django 5.2.4 on 2025-08-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_pago_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='referencia1',
            field=models.CharField(blank=True, db_column='referencia1', max_length=45, null=True),
        ),
    ]
