# Generated by Django 5.2.4 on 2025-08-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_pago_referencia1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='valor',
            field=models.DecimalField(db_column='valor', decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
