# Generated by Django 5.2.6 on 2025-09-08 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_remove_pago_responsable'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(db_column='idAcudiente', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Cédula de extranjería', 'Cédula de extranjería'), ('Pasaporte', 'Pasaporte'), ('Permiso especial de permanencia', 'Permiso especial de permanencia'), ('Otro', 'Otro')], db_column='tipoDoc', max_length=31)),
                ('identification', models.CharField(db_column='identificacion', help_text='Número de documento del acudiente.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('first_name', models.CharField(db_column='nombre', max_length=45)),
                ('last_name', models.CharField(db_column='apellidos', max_length=45)),
                ('city', models.CharField(db_column='ciudad', max_length=45)),
                ('address', models.CharField(db_column='direccion', max_length=100)),
                ('phone', models.CharField(db_column='telefono', help_text='Incluye indicativo si aplica.', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]+$')])),
                ('email', models.EmailField(db_column='correo', max_length=120)),
                ('regime_type', models.CharField(choices=[('Responsable de IVA', 'Responsable de IVA'), ('No responsable de IVA', 'No responsable de IVA')], db_column='tipoRegimen', max_length=45)),
            ],
            options={
                'db_table': 'Acudiente',
            },
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='acudiente',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(db_column='idJugador', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='nombre', max_length=45)),
                ('last_name', models.CharField(db_column='apellido', max_length=45)),
                ('document_type', models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Registro civil', 'Registro civil'), ('Pasaporte', 'Pasaporte'), ('Tarjeta especial de permanencia', 'Tarjeta especial de permanencia'), ('Tarjeta de extranjería', 'Tarjeta de extranjería')], db_column='tipoDoc', max_length=31)),
                ('identification', models.CharField(db_column='identificacion', max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birth_date', models.DateField(db_column='fechaNacimiento')),
                ('birth_city', models.CharField(db_column='ciudadNacimiento', max_length=45)),
                ('address', models.CharField(db_column='direccion', max_length=100)),
                ('city', models.CharField(db_column='ciudad', max_length=45)),
                ('educational_institution', models.CharField(db_column='intitucionE', max_length=60)),
                ('training_session', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], db_column='jornadaEntreno', max_length=15)),
                ('has_disease', models.BooleanField(db_column='enfermedad', default=False)),
                ('disease_type', models.CharField(blank=True, db_column='tipoEnfermedad', max_length=45, null=True)),
                ('has_contraindication', models.BooleanField(db_column='contraindicacion', default=False)),
                ('emergency_contact', models.CharField(db_column='contactoEmergencia', max_length=45)),
                ('contact_number', models.CharField(db_column='numContacto', max_length=20)),
                ('eps', models.CharField(db_column='eps', max_length=15)),
                ('kinship', models.CharField(db_column='parentesco', max_length=30)),
                ('health_center', models.CharField(db_column='centroAtencion', max_length=45)),
                ('pdf_doc_id', models.CharField(db_column='pdfDocId', max_length=100)),
                ('pdf_eps_certificate', models.CharField(db_column='pdfCertificadoEPS', max_length=100)),
                ('fk_guardian', models.ForeignKey(db_column='acudiente', on_delete=django.db.models.deletion.PROTECT, related_name='players', to='user.guardian')),
            ],
            options={
                'db_table': 'Jugador',
            },
        ),
        migrations.DeleteModel(
            name='Acudiente',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
