# Generated by Django 5.2.6 on 2025-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_pago_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('account', models.CharField(choices=[('5031', '5031'), ('5032', '5032')], db_column='cuenta', default='5031', max_length=4)),
                ('date', models.DateField(db_column='fecha')),
                ('description', models.CharField(db_column='descripcion', max_length=45)),
                ('branch', models.CharField(db_column='sucursal', max_length=45)),
                ('reference_1', models.CharField(blank=True, db_column='referencia1', max_length=45, null=True)),
                ('reference_2', models.CharField(blank=True, db_column='referencia2', max_length=45, null=True)),
                ('amount', models.DecimalField(db_column='valor', decimal_places=2, default=0.0, max_digits=12)),
                ('player_name', models.CharField(db_column='nombre', max_length=45)),
                ('reason', models.CharField(db_column='motivo', max_length=50)),
                ('sales_invoice', models.CharField(blank=True, db_column='facturaVenta', max_length=30, null=True)),
                ('receipt', models.CharField(blank=True, db_column='reciboCaja', max_length=20, null=True)),
                ('comment', models.CharField(blank=True, db_column='comentario', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='responsable',
        ),
    ]
