# Generated by Django 5.2.6 on 2025-09-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_remove_pago_responsable'),
        ('user', '0002_guardian_remove_jugador_acudiente_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fk_responsible',
            field=models.ForeignKey(blank=True, db_column='responsable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='user.guardian'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
