# Generated by Django 5.2.4 on 2025-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_fk_responsible_delete_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(db_column='paymentId', primary_key=True, serialize=False),
        ),
    ]
