# Generated by Django 4.2.3 on 2025-10-10 21:26

from django.db import migrations
from django.contrib.auth.models import Group


def create_default_groups(apps, schema_editor):
    """
    Crea los grupos predeterminados del sistema CEFUSA
    """
    # Crear grupo Admin
    admin_group, created = Group.objects.get_or_create(name='Admin')
    if created:
        print("✓ Grupo 'Admin' creado exitosamente")
    else:
        print("→ Grupo 'Admin' ya existe")
    
    # Crear grupo Profesor
    profesor_group, created = Group.objects.get_or_create(name='Profesor')
    if created:
        print("✓ Grupo 'Profesor' creado exitosamente")
    else:
        print("→ Grupo 'Profesor' ya existe")


def reverse_create_default_groups(apps, schema_editor):
    """
    Elimina los grupos predeterminados (para rollback)
    """
    try:
        Group.objects.filter(name__in=['Admin', 'Profesor']).delete()
        print("✓ Grupos predeterminados eliminados")
    except Exception as e:
        print(f"⚠️ Error al eliminar grupos: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),  # Asegurar que auth esté migrado
    ]

    operations = [
        migrations.RunPython(
            create_default_groups,
            reverse_create_default_groups,
            elidable=True,
        ),
    ]
