# Generated by Django 4.2.3 on 2025-10-10 21:29

from django.db import migrations
from django.contrib.auth.models import User, Group


def assign_default_user_roles(apps, schema_editor):
    """
    Asigna roles predeterminados a usuarios específicos del sistema CEFUSA
    """
    # Definir usuarios y sus roles
    user_roles = {
        'ssalazarh': 'Admin',
        'afveleza': 'Admin',
        'smazog': 'Profesor'
    }
    
    for username, role_name in user_roles.items():
        try:
            user = User.objects.get(username=username)
            group = Group.objects.get(name=role_name)
            
            if not user.groups.filter(name=role_name).exists():
                user.groups.add(group)
                print(f"✓ Rol '{role_name}' asignado a usuario '{username}'")
            else:
                print(f"→ Usuario '{username}' ya tiene el rol '{role_name}'")
                
        except User.DoesNotExist:
            print(f"⚠️ Usuario '{username}' no encontrado, se omitirá")
        except Group.DoesNotExist:
            print(f"⚠️ Grupo '{role_name}' no encontrado")


def reverse_assign_default_user_roles(apps, schema_editor):
    """
    Remueve las asignaciones de roles (para rollback)
    """
    user_roles = {
        'ssalazarh': 'Admin',
        'afveleza': 'Admin',
        'smazog': 'Profesor'
    }
    
    for username, role_name in user_roles.items():
        try:
            user = User.objects.get(username=username)
            group = Group.objects.get(name=role_name)
            
            if user.groups.filter(name=role_name).exists():
                user.groups.remove(group)
                print(f"✓ Rol '{role_name}' removido de usuario '{username}'")
                
        except (User.DoesNotExist, Group.DoesNotExist):
            pass  # Ignorar si no existe


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            assign_default_user_roles,
            reverse_assign_default_user_roles,
            elidable=True,
        ),
    ]
