# Generated by Django 5.2.6 on 2025-11-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20251010_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bienvenido a CEFUSA', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('background', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='LandingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('news', 'Noticias'), ('tournaments', 'Torneos'), ('matches', 'Partidos')], default='news', max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/slides/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.landingpage')),
            ],
            options={
                'verbose_name': 'Landing Slide',
                'verbose_name_plural': 'Landing Slides',
                'ordering': ['section', 'order'],
            },
        ),
    ]
