# Generated by Django 5.2.6 on 2025-11-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landingslide',
            unique_together={('section', 'order')},
        ),
    ]
