# Generated by Django 5.2.4 on 2025-08-10 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(db_column='idAcudiente', primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('PEP', 'Permiso especial de permanencia'), ('OTRO', 'Otro')], db_column='tipoDoc', max_length=20)),
                ('identificacion', models.CharField(db_column='identificacion', help_text='Número de documento del acudiente.', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=45)),
                ('ciudad', models.CharField(db_column='ciudad', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('telefono', models.CharField(db_column='telefono', help_text='Incluye indicativo si aplica.', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]+$')])),
                ('correo', models.EmailField(db_column='correo', max_length=120)),
                ('tipo_regimen', models.CharField(choices=[('RESP_IVA', 'Responsable de IVA'), ('NO_RESP_IVA', 'No responsable de IVA')], db_column='tipoRegimen', max_length=45)),
            ],
            options={
                'db_table': 'Acudiente',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(db_column='idJugador', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('apellido', models.CharField(db_column='apellido', max_length=45)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('PA', 'Pasaporte'), ('TEP', 'Tarjeta especial de permanencia'), ('TE', 'Tarjeta de extranjería')], db_column='tipoDoc', max_length=20)),
                ('identificacion', models.CharField(db_column='identificacion', max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('fecha_nacimiento', models.DateField(db_column='fechaNacimiento')),
                ('ciudad_nacimiento', models.CharField(db_column='ciudadNacimiento', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('ciudad', models.CharField(db_column='ciudad', max_length=45)),
                ('institucion_educativa', models.CharField(db_column='intitucionE', max_length=60)),
                ('jornada_entreno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], db_column='jornadaEntreno', max_length=15)),
                ('tiene_enfermedad', models.BooleanField(db_column='enfermedad', default=False)),
                ('tipo_enfermedad', models.CharField(blank=True, db_column='tipoEnfermedad', max_length=45, null=True)),
                ('tiene_contraindicacion', models.BooleanField(db_column='contraindicacion', default=False)),
                ('contacto_emergencia', models.CharField(db_column='contactoEmergencia', max_length=45)),
                ('num_contacto', models.CharField(db_column='numContacto', max_length=20)),
                ('eps', models.CharField(db_column='eps', max_length=15)),
                ('parentesco', models.CharField(db_column='parentesco', max_length=30)),
                ('centro_atencion', models.CharField(db_column='centroAtencion', max_length=45)),
                ('pdf_doc_id', models.CharField(db_column='pdfDocId', max_length=100)),
                ('pdf_certificado_eps', models.CharField(db_column='pdfCertificadoEPS', max_length=100)),
                ('acudiente', models.ForeignKey(db_column='acudiente', on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='users.acudiente')),
            ],
            options={
                'db_table': 'Jugador',
            },
        ),
    ]
